name: flutter_share

description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:                # Importante  
    sdk: flutter
  font_awesome_flutter: ^9.2.0          # Basico
  get: ^4.6.1                           # Basico
  get_storage: ^2.0.3                   # Basico
  google_fonts: ^2.2.0                  # Basico
  supabase: ^0.2.10                     # Basico
  cupertino_icons: ^1.0.2           
  share_plus: ^3.1.0
  http: ^0.13.4
  file_picker: ^4.5.0
  image_picker: ^0.8.4+10
  path_provider: ^2.0.9

dev_dependencies:

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  assets:
    - assets/imagens/

  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf
